# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ShellAi < Formula
  desc ""
  homepage "https://github.com/ibigio/shell-ai"
  version "1.2.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ibigio/shell-ai/releases/download/v1.2.1/shell-ai_Darwin_x86_64.tar.gz"
      sha256 "c3aa9ae12179e3ab3b140f64bc69f19dc35e7e1df510d2d7dc86cf25b1f16be3"

      def install
        bin.install "shell-ai"
        bin.install_symlink "shell-ai" => "q"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ibigio/shell-ai/releases/download/v1.2.1/shell-ai_Darwin_arm64.tar.gz"
      sha256 "0818271ea32767e7dd7a12c60b34a17bf3b5ba748b85e0051aaf86b98f969cc1"

      def install
        bin.install "shell-ai"
        bin.install_symlink "shell-ai" => "q"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ibigio/shell-ai/releases/download/v1.2.1/shell-ai_Linux_x86_64.tar.gz"
        sha256 "70d0d5417371f07c97699b17b2420346c4e88546aca454419b0888aef5060410"

        def install
          bin.install "shell-ai"
          bin.install_symlink "shell-ai" => "q"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ibigio/shell-ai/releases/download/v1.2.1/shell-ai_Linux_arm64.tar.gz"
        sha256 "8a5ebc30fb79cd188decf9f10b15e8030c04ab910d82666a279c3af5750bd893"

        def install
          bin.install "shell-ai"
          bin.install_symlink "shell-ai" => "q"
        end
      end
    end
  end
end
